In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\ASUS\OneDrive\Desktop\Learning Python,file sorter,webscraping\world_population.csv")

In [5]:
df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [38]:
df[df['Rank'] <=10] #shows data where rank is less or equal to 10

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
16,8,BGD,Bangladesh,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
27,7,BRA,Brazil,Brasilia,South America,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
93,4,IDN,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
131,10,MEX,Mexico,Mexico City,North America,1.275041e+08,1.259983e+08,1.201499e+08,1.125324e+08,9.787344e+07,8.172043e+07,67705186.0,50289306.0,1964375.0,64.9082,1.0063,1.60
149,6,NGA,Nigeria,Abuja,Africa,2.185412e+08,2.083274e+08,1.839958e+08,1.609529e+08,1.228520e+08,9.521426e+07,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
156,5,PAK,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
171,9,RUS,Russia,Moscow,Europe,1.447133e+08,1.456173e+08,1.446684e+08,1.432426e+08,1.468448e+08,1.480057e+08,138257420.0,130093010.0,17098242.0,8.4636,0.9973,1.81
221,3,USA,United States,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24

In [100]:
df[df['Rank'] <=10].sort_values(by = 'Rank') #sorts out data 1 to 10 in order ie ascending order

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
221,3,USA,United States,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
93,4,IDN,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
156,5,PAK,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
149,6,NGA,Nigeria,Abuja,Africa,2.185412e+08,2.083274e+08,1.839958e+08,1.609529e+08,1.228520e+08,9.521426e+07,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
27,7,BRA,Brazil,Brasilia,South America,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
16,8,BGD,Bangladesh,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
171,9,RUS,Russia,Moscow,Europe,1.447133e+08,1.456173e+08,1.446684e+08,1.432426e+08,1.468448e+08,1.480057e+08,138257420.0,130093010.0,17098242.0,8.4636,0.9973,1.81
131,10,MEX,Mexico,Mexico City,North America,1.275041e+08,1.259983e+08,1.201499e+08,1.125324e+08,9.787344e+07,8.172043e+07,67705186.0,50289306.0,1964375.0,64.9082,1.0063,1.60

In [102]:
df[df['Rank'] <=10].sort_values(by = 'Rank', ascending =False) #sorts out data 10 to 1 in order ie descending order

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
131,10,MEX,Mexico,Mexico City,North America,1.275041e+08,1.259983e+08,1.201499e+08,1.125324e+08,9.787344e+07,8.172043e+07,67705186.0,50289306.0,1964375.0,64.9082,1.0063,1.60
171,9,RUS,Russia,Moscow,Europe,1.447133e+08,1.456173e+08,1.446684e+08,1.432426e+08,1.468448e+08,1.480057e+08,138257420.0,130093010.0,17098242.0,8.4636,0.9973,1.81
16,8,BGD,Bangladesh,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
27,7,BRA,Brazil,Brasilia,South America,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
149,6,NGA,Nigeria,Abuja,Africa,2.185412e+08,2.083274e+08,1.839958e+08,1.609529e+08,1.228520e+08,9.521426e+07,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
156,5,PAK,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
93,4,IDN,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
221,3,USA,United States,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88

In [104]:
df[df['Rank'] <=10].sort_values(by = ['Country','Rank']) 
#sorts out data country being the first to be considered then the rank

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
16,8,BGD,Bangladesh,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
27,7,BRA,Brazil,Brasilia,South America,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
93,4,IDN,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
131,10,MEX,Mexico,Mexico City,North America,1.275041e+08,1.259983e+08,1.201499e+08,1.125324e+08,9.787344e+07,8.172043e+07,67705186.0,50289306.0,1964375.0,64.9082,1.0063,1.60
149,6,NGA,Nigeria,Abuja,Africa,2.185412e+08,2.083274e+08,1.839958e+08,1.609529e+08,1.228520e+08,9.521426e+07,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
156,5,PAK,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
171,9,RUS,Russia,Moscow,Europe,1.447133e+08,1.456173e+08,1.446684e+08,1.432426e+08,1.468448e+08,1.480057e+08,138257420.0,130093010.0,17098242.0,8.4636,0.9973,1.81
221,3,USA,United States,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24

In [118]:
df[df['Rank'] <=10].sort_values(by = ['Capital','Continent'], ascending = [True,False]) 
#sorts out data capital being the first to be considered then the continent. #ordering capital in ascending order, continent descending order

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
149,6,NGA,Nigeria,Abuja,Africa,2.185412e+08,2.083274e+08,1.839958e+08,1.609529e+08,1.228520e+08,9.521426e+07,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
27,7,BRA,Brazil,Brasilia,South America,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
16,8,BGD,Bangladesh,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
156,5,PAK,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
93,4,IDN,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
131,10,MEX,Mexico,Mexico City,North America,1.275041e+08,1.259983e+08,1.201499e+08,1.125324e+08,9.787344e+07,8.172043e+07,67705186.0,50289306.0,1964375.0,64.9082,1.0063,1.60
171,9,RUS,Russia,Moscow,Europe,1.447133e+08,1.456173e+08,1.446684e+08,1.432426e+08,1.468448e+08,1.480057e+08,138257420.0,130093010.0,17098242.0,8.4636,0.9973,1.81
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
221,3,USA,United States,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24

In [84]:
specific_country = ['Brazil','China']
df[df['Country'].isin (specific_country)] #shows specific countries we are looking for in the Country column

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
27,7,BRA,Brazil,Brasilia,South America,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88

In [82]:
df[df['Continent'].str.contains('Africa')] #shows data contained in the continent column where string is'Africa'

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
5,42,AGO,Angola,Luanda,Africa,35588987.0,33428485.0,28127721.0,23364185.0,16394062.0,11828638.0,8330047.0,6029700.0,1246700.0,28.5466,1.0315,0.45
21,77,BEN,Benin,Porto-Novo,Africa,13352864.0,12643123.0,10932783.0,9445710.0,6998023.0,5133419.0,3833939.0,3023443.0,112622.0,118.5635,1.0274,0.17
26,144,BWA,Botswana,Gaborone,Africa,2630296.0,2546402.0,2305171.0,2091664.0,1726985.0,1341474.0,938578.0,592244.0,582000.0,4.5194,1.0162,0.03
31,58,BFA,Burkina Faso,Ouagadougou,Africa,22673762.0,21522626.0,18718019.0,16116845.0,11882888.0,9131361.0,6932967.0,5611666.0,272967.0,83.0641,1.0259,0.28
32,78,BDI,Burundi,Bujumbura,Africa,12889576.0,12220227.0,10727148.0,9126605.0,6307659.0,5483793.0,4312834.0,3497834.0,27834.0,463.0874,1.0270,0.16
34,53,CMR,Cameroon,Yaounde,Africa,27914536.0,26491087.0,23012646.0,19878036.0,15091594.0,11430520.0,8519891.0,6452787.0,475442.0,58.7128,1.0263,0.35
36,171,CPV,Cape Verde,Praia,Africa,593149.0,582640.0,552166.0,521212.0,458251.0,364563.0,317234.0,287262.0,4033.0,147.0739,1.0089,0.01
38,117,CAF,Central African Republic,Bangui,Africa,5579144.0,5343020.0,4819333.0,4660067.0,3759170.0,2809221.0,2415276.0,2067356.0,622984.0,8.9555,1.0224,0.07
39,69,TCD,Chad,N'Djamena,Africa,17723315.0,16644701.0,14140274.0,11894727.0,8259137.0,5827069.0,4408230.0,3667394.0,1284000.0,13.8032,1.0316,0.22
43,163,COM,Comoros,Moroni,Africa,836774.0,806166.0,730216.0,656024.0,536758.0,431119.0,328328.0,242351.0,1862.0,449.3953,1.0184,0.01
52,160,DJI,Djibouti,Djibouti,Africa,1120849.0,1090156.0,1006259.0,919199.0,742033.0,577173.0,324121.0,144379.0,23200.0,48.3125,1.0138,0.01
55,15,COD,DR Congo,Kinshasa,Africa,99010212.0,92853164.0,78656904.0,66391257.0,48616317.0,35987541.0,26708686.0,20151733.0,2344858.0,42.2244,1.0325,1.24
57,14,EGY,Egypt,Cairo,Africa,110990103.0,107465134.0,97723799.0,87252413.0,71371371.0,57214630.0,43748556.0,34781986.0,1002450.0,110.7188,1.0158,1.39
59,152,GNQ,Equatorial Guinea,Malabo,Africa,1674908.0,1596049.0,NaN,1094524.0,684977.0,465549.0,282509.0,316955.0,28051.0,59.7094,1.0247,0.02
60,132,ERI,Eritrea,Asmara,Africa,3684032.0,3555868.0,3340006.0,3147727.0,2392880.0,2149960.0,1657982.0,1272748.0,117600.0,31.3268,1.0176,0.05
62,159,SWZ,Eswatini,Mbabane,Africa,NaN,1180655.0,1133936.0,1099920.0,1030496.0,854011.0,598564.0,442865.0,17364.0,69.2047,1.0079,0.02
63,12,ETH,Ethiopia,Addis Ababa,Africa,123379924.0,117190911.0,102471895.0,89237791.0,67031867.0,47878073.0,34945469.0,28308246.0,1104300.0,111.7268,1.0257,1.55
71,146,GAB,Gabon,Libreville,Africa,2388992.0,2292573.0,2028517.0,1711105.0,1272935.0,983028.0,749078.0,597192.0,267668.0,8.9252,1.0204,0.03
72,142,GMB,Gambia,Banjul,Africa,2705992.0,2573995.0,2253133.0,NaN,NaN,NaN,NaN,NaN,10689.0,253.1567,1.0250,0.03
75,47,GHA,Ghana,Accra,Africa,33475870.0,32180401.0,28870939.0,25574719.0,19665502.0,15446982.0,11865246.0,8861895.0,238533.0,140.3406,1.0196,0.42
84,75,GIN,Guinea,Conakry,Africa,13859341.0,13205153.0,11625998.0,10270728.0,8336967.0,6354145.0,4972609.0,4222374.0,245857.0,56.3716,1.0242,0.17
85,149,GNB,Guinea-Bissau,Bissau,Africa,2105566.0,2015828.0,1788919.0,1567220.0,1230849.0,973551.0,831462.0,591663.0,36125.0,58.2856,1.0218,0.03
100,52,CIV,Ivory Coast,Yamoussoukro,Africa,28160542.0,26811790.0,23596741.0,21120042.0,16799670.0,11910540.0,8303809.0,5477086.0,322463.0,NaN,NaN,0.35
106,27,KEN,Kenya,Nairobi,Africa,54027487.0,51985780.0,46851488.0,41517895.0,30851606.0,23162269.0,16187124.0,11473087.0,580367.0,93.0919,1.0193,0.68
113,147,LSO,Lesotho,Maseru,Africa,2305825.0,2254100.0,2118521.0,2022747.0,1998630.0,1798997.0,1407672.0,1023481.0,30355.0,75.9620,1.0107,0.03
114,121,LBR,Liberia,Monrovia,Africa,5302681.0,5087584.0,4612329.0,4019956.0,2895224.0,2209731.0,1932169.0,1463563.0,111369.0,47.6136,1.0210,0.07
115,107,LBY,Libya,Tripoli,Africa,6812341.0,6653942.0,6192235.0,6491988.0,5154790.0,4236983.0,2962720.0,1909177.0,1759540.0,3.8717,1.0114,0.09
120,50,MDG,Madagascar,Antananarivo,Africa,29611714.0,28225177.0,24850912.0,21731053.0,16216431.0,11882762.0,8948162.0,6639751.0,587041.0,50.4423,1.0241,0.37
121,62,MWI,Malawi,Lilongwe,Africa,20405317.0,19377061.0,16938942.0,14718422.0,11229387.0,9539665.0,6267369.0,4625141.0,118484.0,172.2200,1.0259,0.26
124,59,MLI,Mali,Bamako,Africa,22593590.0,21224040.0,18112907.0,15529181.0,11239101.0,8945026.0,7372581.0,6153587.0,1240192.0,18.2178,1.0314,0.28
128,126,MRT,Mauritania,Nouakchott,Africa,4736139.0,4498604.0,3946220.0,3419461.0,2695003.0,2006027.0,1506694.0,1122198.0,1030700.0,4.5951,1.0263,0.06
129,157,MUS,Mauritius,Port Louis,Africa,1299469.0,1297828.0,1293153.0,1283330.0,1215930.0,1090290.0,954865.0,830115.0,2040.0,636.9946,1.0004,0.02
130,182,MYT,Mayotte,Mamoudzou,Africa,326101.0,305587.0,249545.0,211786.0,159215.0,92659.0,52233.0,35383.0,374.0,871.9278,1.0319,0.00
138,40,MAR,Morocco,Rabat,Africa,37457971.0,36688772.0,34680458.0,32464865.0,28554415.0,24570814.0,19678444.0,15274351.0,446550.0,83.8830,1.0103,0.47
139,48,MOZ,Mozambique,Maputo,Africa,32969517.0,31178239.0,NaN,NaN,17768505.0,13303459.0,11413587.0,8411676.0,801590.0,41.1302,1.0278,0.41
141,145,NAM,Namibia,Windhoek,Africa,2567012.0,2489098.0,2282704.0,2099271.0,1819141.0,1369011.0,975994.0,754467.0,825615.0,3.1092,1.0146,0.03
148,54,NER,Niger,Niamey,Africa,26207977.0,24333639.0,20128124.0,16647543.0,11622665.0,8370647.0,6173177.0,4669708.0,1267000.0,20.6851,1.0378,0.33
149,6,NGA,Nigeria,Abuja,Africa,218541212.0,208327405.0,183995785.0,160952853.0,122851984.0,95214257.0,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
168,114,COG,Republic of the Congo,Brazzaville,Africa,5970424.0,5702174.0,5064386.0,4437884.0,3134030.0,2385435.0,1829256.0,1396989.0,342000.0,17.4574,1.0231,0.07
169,161,REU,Reunion,Saint-Denis,Africa,974052.0,957822.0,922495.0,890130.0,785424.0,658992.0,551674.0,473925.0,2511.0,387.9140,1.0082,0.01
172,76,RWA,Rwanda,Kigali,Africa,13776698.0,13146362.0,11642959.0,10309031.0,8109989.0,7319962.0,5247532.0,3896367.0,26338.0,523.0731,1.0234,0.17
181,187,STP,Sao Tome and Principe,São Tomé,Africa,227380.0,218641.0,201124.0,182138.0,143714.0,120343.0,97210.0,77583.0,964.0,235.8714,1.0192,0.00
183,72,SEN,Senegal,Dakar,Africa,17316449.0,16436119.0,14356181.0,12530121.0,9704287.0,7536001.0,5703869.0,4367744.0,NaN,NaN,1.0261,0.22
185,196,SYC,Seychelles,Victoria,Africa,107118.0,105530.0,99240.0,92409.0,80060.0,71057.0,65290.0,54379.0,452.0,236.9867,1.0061,0.00
186,102,SLE,Sierra Leone,Freetown,Africa,8605718.0,8233969.0,7314773.0,6436698.0,4584067.0,4325388.0,3367477.0,2778557.0,71740.0,119.9570,1.0220,0.11
192,70,SOM,Somalia,Mogadishu,Africa,17597511.0,16537016.0,13763906.0,12026649.0,8721465.0,6999096.0,5892224.0,NaN,637657.0,27.5971,1.0312,0.22
193,24,ZAF,South Africa,Pretoria,Africa,59893885.0,58801927.0,55876504.0,51784921.0,46813266.0,39877570.0,29463549.0,22368306.0,1221037.0,49.0517,1.0084,0.75
195,86,SSD,South Sudan,Juba,Africa,10913164.0,10606227.0,11194299.0,NaN,6114440.0,4750817.0,4192011.0,3342410.0,619745.0,17.6091,1.0153,0.14
198,32,SDN,Sudan,Khartoum,Africa,46874204.0,44440486.0,38171178.0,33739933.0,26298773.0,21090886.0,16673586.0,11305206.0,1886068.0,24.8529,1.0267,0.59
205,22,TZA,Tanzania,Dodoma,Africa,65497748.0,61704518.0,52542823.0,45110527.0,34463704.0,26206012.0,19297659.0,13618192.0,945087.0,69.3034,1.0300,0.82
208,100,TGO,Togo,Lomé,Africa,8848699.0,8442580.0,7473229.0,6571855.0,5008035.0,3875947.0,2838110.0,2197383.0,56785.0,155.8281,1.0236,0.11
212,79,TUN,Tunisia,Tunis,Africa,12356117.0,12161723.0,11557779.0,10895063.0,9893316.0,8440023.0,6578156.0,5047404.0,163610.0,75.5218,1.0076,0.15
217,31,UGA,Uganda,Kampala,Africa,47249585.0,44404611.0,37477356.0,32341728.0,24020697.0,17586630.0,13284026.0,10317212.0,241550.0,195.6100,1.0304,0.59
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [14]:
df2 = df.set_index('Country') #changing and setting the index as country.
df2

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [76]:
df2.filter(items = ['Capital','Continent','CCA3']) #we get to filter data and choose what we want to see

                            Capital Continent CCA3
Country
Afghanistan                   Kabul      Asia  AFG
Albania                      Tirana    Europe  ALB
Algeria                     Algiers    Africa  DZA
American Samoa            Pago Pago   Oceania  ASM
Andorra            Andorra la Vella    Europe  AND
...                             ...       ...  ...
Wallis and Futuna          Mata-Utu   Oceania  WLF
Western Sahara             El Aaiún    Africa  ESH
Yemen                         Sanaa      Asia  YEM
Zambia                       Lusaka    Africa  ZMB
Zimbabwe                     Harare    Africa  ZWE

[234 rows x 3 columns]

In [75]:
df2.filter(items = ['Brazil'], axis = 0) #filtering

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Brazil,7,BRA,Brasilia,South America,215313498.0,213196304.0,205188205.0,196353492.0,175873720.0,150706446.0,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.7

In [88]:
df2.filter(like = 'United', axis = 0)

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
United Arab Emirates,97,ARE,Abu Dhabi,Asia,9441129.0,9287289.0,8916899.0,8481771.0,3275333.0,1900151.0,1014048.0,298084.0,83600.0,112.9322,1.0081,0.12
United Kingdom,21,GBR,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85
United States,3,USA,"Washington, D.C.",North America,338289857.0,335942003.0,324607776.0,311182845.0,282398554.0,248083732.0,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
United States Virgin Islands,200,VIR,Charlotte Amalie,North America,99465.0,100442.0,102803.0,106142.0,108185.0,100685.0,96640.0,63446.0,347.0,286.6427,0.9937,0.00

In [16]:
df2.loc['United States'] #finding location of a specific string

Rank                                          3
CCA3                                        USA
Capital                        Washington, D.C.
Continent                         North America
2022 Population                     338289857.0
2020 Population                     335942003.0
2015 Population                     324607776.0
2010 Population                     311182845.0
2000 Population                     282398554.0
1990 Population                     248083732.0
1980 Population                     223140018.0
1970 Population                     200328340.0
Area (km²)                            9372610.0
Density (per km²)                       36.0935
Growth Rate                              1.0038
World Population Percentage                4.24
Name: United States, dtype: object

In [18]:
df2.iloc[4] #looks for specified interger location ie 4

Rank                                        203
CCA3                                        AND
Capital                        Andorra la Vella
Continent                                Europe
2022 Population                         79824.0
2020 Population                         77700.0
2015 Population                         71746.0
2010 Population                         71519.0
2000 Population                         66097.0
1990 Population                         53569.0
1980 Population                         35611.0
1970 Population                         19860.0
Area (km²)                                468.0
Density (per km²)                      170.5641
Growth Rate                                1.01
World Population Percentage                 0.0
Name: Andorra, dtype: object